import type React from 'react'
import type { Metadata } from 'next'
import { ThemeProvider } from '@/components/themes/theme-provider'
import { UserPrefsSettings } from '@/components/themes/prefs'

import '@/styles/globals.css'

export const metadata: Metadata = {
    title: 'To-do List',
    description: 'Generated by create next app',
    icons: {
        icon: 'src/app/favicon.ico',
    },
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <ThemeProvider
                    defaultTheme="system"
                    defaultColorTheme="default"
                >  
                    <div className="relative min-h-screen">
                        <main className="flex-1">{children}</main>
                        <div className="fixed right-10 bottom-10">
                            <UserPrefsSettings />
                        </div>
                        <footer></footer>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    )
}